name: Agro Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repostitory
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.1.0
        with:
          boost_version: 1.73.0
          platform_version: 18.04
      - name: Build app
        id: build-app
        run: |
          echo "Boost: " $BOOST_ROOT
          mkdir build
          cd build
          cmake -DWITH_SSL=0 -DBOOST_PATH=$BOOST_ROOT ..
          cmake -build .
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
