name: Build
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ssl:
        description: Compile with SSL
        required: true
        default: '1'
env:
  WITH_SSL: ${{ github.event.inputs.ssl || '1' }}
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Ubuntu GCC
            os: ubuntu-latest
            cc: gcc
            cxx: g++
          - name: Ubuntu Clang
            os: ubuntu-latest
            cc: clang
            cxx: clang++
    steps:
      - name: Checking out repostitory
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.1.0
        with:
          boost_version: 1.73.0
          platform_version: 18.04
      - name: Build app
        id: build-app
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx}} \
                -DWITH_SSL=$WITH_SSL -DBOOST_PATH=$BOOST_ROOT ..
          cmake --build .
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}