name: Build
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ssl:
        description: Compile with SSL
        required: true
        default: '1'
env:
  ssl: ${{ github.event.inputs.ssl || '1' }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repostitory
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.1.0
        with:
          boost_version: 1.73.0
          platform_version: 18.04
      - name: Build app
        id: build-app
        run: |
          mkdir build
          cd build
          cmake -DWITH_SSL=$WITH_SSL -DBOOST_PATH=$BOOST_ROOT ..
          cmake --build .
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          WITH_SSL: ${{ env.ssl }}